# MATH10098: Numerical Linear Algebra - Python recap

The computing component of the course uses Jupyter Notebooks as a support. This is a notebook to refresh your Python programming skills, and to recap some useful Python commands to handle operations with matrices and vectors.

Familiarity with Python is assumed for this course -- make sure you are comfortable with all the code in this notebook. If a function is used here that you do not recognise, [the official Python documentation page](https://docs.python.org/3/) has a search box on the top right, where you can search for the appropriate documentation. Alternatively, type

```python
help(some_function)
```

to display some help text describing `some_function`.


## Jupyter notebooks

A **Jupyter notebook** allows to present text, typeset maths, images, and interactive Python code together in one document. Jupyter notebooks are edited and viewed in a web browser.

A notebook consists of several **cells**, which can be of 2 main types:
* **Markdown cells**, like this one, contain text formatted using Markdown. They can be edited by double-clicking on them. Markdown syntax is straightforward -- you can double-click on the Markdown cells in this notebook to view the source text. Markdown syntax also supports LaTeX typesetting for maths, both inline using `$...$`, e.g. $f: \mathbb{R}^2 \to \mathbb{R}$, and in display mode using `$$...$$`, e.g.

$$ \frac{\partial f}{\partial y} = 2e^{-x} \cos(y). $$

* **Code cells**, like the one just below, in which we can type and run Python code interactively. They are indicated by `In [ ]:` on the left hand side.

To **run** a cell (i.e. to typeset Markdown cells or to execute code cells), click the "<kbd>>| Run</kbd>" button on the toolbar above, or press <kbd>Shift</kbd> + <kbd>Enter</kbd>.

Note that each time you run the cell, the number inside `In [x]:` increments by 1 -- this is just to indicate the number of inputs made to Python in a session.

In [1]:
print('This is a code cell!')
print(3 + 8)

This is a code cell!
11


To select a cell, click on it (a blue frame should appear around the cell). You can click on the **`+`** button in the toolbar above to insert a new cell below, and change the cell type to "Code" or "Markdown" by using the drop-down menu in the toolbar.

For the workshops and the projects, you will work with Jupyter notebooks. Make sure you are familiar and comfortable with using them.

---
**Learn more:**
* [Jupyter Notebook documentation](https://jupyter-notebook.readthedocs.io/en/stable/)
* [Project Jupyter](https://jupyter.org/)
* [A gallery of interesting Jupyter notebooks](https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks)
* [Markdown cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
---

## Python fundamentals


### Defining variables

We can assign values to variables, and display these values using the `print` function. Code comments start with the `#` character. In Jupyter notebooks, you can also select any code you'd like to comment out (or uncomment), and press <kbd>Ctrl</kbd>+<kbd>/</kbd> to toggle code comments.

**Round brackets** `()` are generally used for function calls (and *tuples*, if you are familiar with them). **Square brackets** `[]` are used to *index* sequences and arrays, and to create lists.

Note that **Python indexes from 0** -- that is, the first element of a sequence `x` is accessed via `x[0]`.

In [1]:
# This is a comment, starting with the '#' character.

# Assign some variables
a = 0.5
b = 'hello world!'
c = [2, 1, 1]

# Print their values and types
print(a, type(a))
print(b, type(b))
print(c, type(c))

# Append a and b to the end of the list c
c.append(a)
c.append(b)
print(c)
print(len(c))

# Print some elements and slices of c -- pay attention to the indexes!
print(c[0])
print(c[-1])
print(c[1:3])
print(c[:3])
print(c[3:])

0.5 <class 'float'>
hello world! <class 'str'>
[2, 1, 1] <class 'list'>
[2, 1, 1, 0.5, 'hello world!']
5
2
hello world!
[1, 1]
[2, 1, 1]
[0.5, 'hello world!']


---
**Note:** when starting a Jupyter Notebook, we start an interactive *session*. This means that if a variable is created somewhere in the notebook, then it will be available for the rest of the session (unless explicitly deleted), and accessible from any code cell.

For example, after assigning values to `a`, `b`, and `c` here (and running the cell), typing `print(a)` in the first (or any other) code cell in the notebook will display `0.5` -- try it for yourself.

---

### Loops

We can write `for` loops and `while` loops to iterate a process:

In [2]:
# Print the type of each element of the list c
for i in c:
    print(type(i))
    
# Loop over a range
for j in range(4):
    print(j)

# Add powers of 2 until the sum surpasses 1 million
s = 2
k = 1
while s <= 1e6:
    k += 1       # equivalent to k = k + 1
    s += 2**k

print(s)

<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>
<class 'str'>
0
1
2
3
1048574


Note that the way Python knows which instructions are in the loop is by looking at the indentation level of the commands following the `for` statement. The value printed at the end is only printed once, because it is *outside* the loop.

### `if`-`elif`-`else` blocks

To execute code under certain conditions only, we can use `if`-`elif`-`else` blocks (`elif` is short for "else if"). The syntax is
```python
if cond_1:
    # [some instructions, executed if cond_1 is true]
elif cond_2:
    # [other instructions, executed if cond_1 is false,
    # but cond_2 is true]
else:
    # [other instructions, executed if both cond_1 and cond_2
    # are false]
```
Note, in particular, that the conditions in an `if`-`elif`-`else` block are checked in order, and **only one** branch is executed.


### Functions

A **function** is essentially a block of code which only *executes* when the function is *called*. A Python function can be defined using
```python
def my_func(inputs):
    [function body]
    return outputs
```
where
* `my_func` is the *name* of your function,
* `inputs` are the (zero or more) **input arguments**,
* `[function body]` are the commands to execute upon *calling* the function,
* `outputs` are the (one or more) **output values**.

It is good practice to write a **docstring** for your functions -- a string, as the first line of your function body, which describes what the function does, and what are the input and output values.

In [ ]:
def sum_diff_prod(a, b):
    """
    Computes and returns the sum, difference,
    and product of a and b.
    """
    return a+b, a-b, a*b

# This function returns 3 values -- we can assign them to separate variables
s, d, p = sum_diff_prod(10, 4)
print(d)

---
### Documentation links

#### Variables and types
* [Data model: objects, values, and types](https://docs.python.org/3/reference/datamodel.html)
* [Lists](https://docs.python.org/3/tutorial/introduction.html#lists)
* [More on lists](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists)
* [Sequence types: list, tuple, range](https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range)

#### Loops and flow control
* [The `for` statement](https://docs.python.org/3/tutorial/controlflow.html#for-statements)
* [Ranges](https://docs.python.org/3/library/stdtypes.html#typesseq-range)
* [Looping techniques](https://docs.python.org/3/tutorial/datastructures.html#looping-techniques)
* [First steps towards programming - The `while` loop](https://docs.python.org/3/tutorial/introduction.html#first-steps-towards-programming)
* [The `while` statement](https://docs.python.org/3/reference/compound_stmts.html#while)
* [More flow control tools](https://docs.python.org/3/tutorial/controlflow.html)
* [Boolean operations](https://docs.python.org/3/reference/expressions.html#boolean-operations)
* [`break` and `continue` statements, and `else` clauses on loops](https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops)

#### Functions
* [Defining Functions](https://docs.python.org/3/tutorial/controlflow.html#defining-functions)
* [More on Defining Functions](https://docs.python.org/3/tutorial/controlflow.html#more-on-defining-functions)

---

## Matrices and vectors: Numpy arrays

To create and operate on vectors and matrices in Python, [the **Numpy module**](https://docs.scipy.org/doc/numpy/) is generally used, more specifically its **`ndarray` type** (stands for "N-dimensional array"). Numpy arrays are *containers*, like lists or tuples, which allow us to store and handle vectors and matrices efficiently. (If you are familiar with MATLAB, Numpy arrays are quite similar to MATLAB arrays.)

Because Numpy is not part of vanilla Python, we first need to **import** the module to use its functions, using
```python
import numpy as np
```

### Creating arrays

The function `np.array()` is then used to create an array. It takes a **list** as an input argument, and returns an array where the rows are the elements of the list. For example, to create a vector or a matrix:

In [3]:
import numpy as np

# Create a vector
v = np.array([3, 4, -2.8, 0])
print(v)
print(type(v))

# Create a matrix: pass a list of lists to np.array(),
# each element of which is a row of the matrix
id_4 = np.array([[1, 0, 0, 0],
                 [0, 1, 0, 0],
                 [0, 0, 1, 0],
                 [0, 0, 0, 1]], dtype=float)

print(id_4)

[ 3.   4.  -2.8  0. ]
<class 'numpy.ndarray'>
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


**Note:** 1-D Numpy arrays (vectors) are *not* row vectors or column vectors -- they are similar to lists, in this sense.

Numpy also has many useful functions to construct arrays with particular properties:

In [4]:
# Create a 3 x 7 matrix of zeros
A = np.zeros((3, 7))
print(A)

# Create a vector of ones
u = np.ones((5,))
print(u)

# Create a diagonal matrix from a vector
U = np.diag(u)
print(U)

# Create the 4x4 identity matrix, as above
id_4_mat = np.eye(4)
print(id_4_mat)

# Create a matrix of pseudo-random numbers between 0 and 1,
# sampled from a uniform distribution
B = np.random.rand(3, 3)
print(B)

# Create a 1D array with a range of floats
v = np.arange(3.1, 5.2, 0.3)
print(v)

# Retrieve the dimensions of an array, as a tuple
print(A.shape)
print(A.shape[0])    # print the first element of A.shape,
                     # i.e. the number of rows of A

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
[ 1.  1.  1.  1.  1.]
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.16579474  0.27903572  0.22715645]
 [ 0.70162418  0.87258178  0.4428097 ]
 [ 0.39109344  0.02411982  0.18763092]]
[ 3.1  3.4  3.7  4.   4.3  4.6  4.9  5.2]
(3, 7)
3


For those functions which require to specify the dimensions of the target array, these dimensions are given as *one argument* -- a **sequence of integers**. This is why the command
```python
A = np.zeros((3, 7))
```
requires the double parentheses -- only one argument is given to `np.zeros`, which is the tuple `(3, 7)`.

We can also load an array from an external `.npy` file, and save an array to an external file, using the functions `np.load` and `np.save`:

In [ ]:
# Create a matrix and save it in the current directory
A = np.random.rand(2, 4)
print(A)
np.save('my_mat.npy', A)

# Load the file to recover the matrix
M = np.load('my_mat.npy')
print(M)

### Array operations

The basic operators `+`, `-`, `*`, `/`, and `**` can be used to perform **element-wise** operations between
* two arrays of the *same size*, or
* an array and a scalar.

Numpy has a sub-module called `np.linalg`, which contains many useful functions for linear algebra and matrix operations. For example, while `A * B` returns the *element-wise* product of `A` and `B`, the function `np.matmul()` (and its operator alias, `@`) allows to compute **matrix products**.

In [ ]:
A = 2 * np.ones((2, 4))
print("A =")
print(A)

B = 0.4 * np.eye(4)
print("B =")
print(B)

v = np.random.random((4,))
print("v =")
print(v)

# Products AB and BA^T
print(np.matmul(A, B))
print(np.matmul(B, A.T))
print(np.matmul(B, A.transpose()))

# Products Av and v^T B
print(np.matmul(A, v))
print(np.matmul(v, B))

# Dot product of v with itself
print(np.matmul(v, v))

# We can also use the operator @ to do exactly the same thing:
print(B @ A.T)
print(A @ v)
print(v @ B)
print(v @ v)

Note the different behaviours of `np.matmul()`, depending on the dimensions of its arguments. All cases are outlined in the documentation linked below. Also note the `.T` notation used to **transpose** arrays.

Here are some useful functions provided by the `np.linalg` submodule, which we will use in the course:

In [ ]:
A = np.random.rand(3, 3)
b = np.ones((3,))

print('\nInverse and determinant:')
print("A^(-1) =", np.linalg.inv(A))  # Inverse of a matrix
print("det(A) =", np.linalg.det(A))  # Determinant of a matrix

print('\nSolution of Ax = b:')
print("x =", np.linalg.solve(A, b))  # Solve Ax = b for x

### Array indexing and slicing

In [ ]:
# Create a matrix using the np.arange and np.reshape functions
A = np.arange(1/4, 17/4, 1/4).reshape((4, 4))
print(A)

# Print some elements and slices of A
print(A[1, 3])
print(A[0, :])    # row 0, all elements
print(A[:, 2])    # all elements, column 2
print(A[2:, :-1]) # rows 2 to the last, columns 0 to the second-to-last

print(A[0::2, 1]) # every second row starting from 0, column 1

### Array copying

By default, assigning the values in a Numpy array (or a slice of an array) to a new variables **does not copy the values** into a new place in memory. Instead, a new **reference** to the old array (or slice) is defined, which still points to the original values. This is sometimes referred to as creating a *view* of all or part of the old array.

In [ ]:
import numpy as np

# Create an array A
A = np.array([3, 2, 4, 5])

# Create an array B with the first 2 values of A
B = A[:2]

# Change the first value of B
B[0] = 0

# Print A and B -- both have changed!
print(A)
print(B)

In the example above, `B` is simply a *view* of the first 2 values of `A` -- this means that `B[0]` still refers, in memory, to the first value of `A`. When `B[0]` is assigned a new value, so is `A[0]` -- only one number is changed in memory, using one of its two names.

In order to avoid this behaviour, make sure to **copy** the values in `A` and assign these to `B` in the second step. You can do so using the function `np.copy`:

In [ ]:
import numpy as np

# Create an array A
A = np.array([3, 2, 4, 5])

# Create an array B with the same values as A
B = np.copy(A)

# Change the first value of B
B[0] = 0

# Print A and B -- now, only B has changed.
print(A)
print(B)

### Documentation links

* [NumPy User Guide](https://docs.scipy.org/doc/numpy/user/)
* [NumPy Reference](https://docs.scipy.org/doc/numpy/reference/index.html)

#### Array creation
* [NumPy array function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)
* [The N-dimensional array (ndarray)](https://docs.scipy.org/doc/numpy-1.12.0/reference/arrays.ndarray.html)
* [Array creation routines](https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.array-creation.html#routines-array-creation)
* [numpy.random](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

#### Array operations
* [numpy.linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
* [numpy.matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)

#### Array copy
* [numpy.copy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html)

---

## Timing and reporting

### Timing a computation

The `time` module provides the `time.time` function, which returns the current (absolute) time, in seconds. We can use this to evaluate how much time a piece of code takes to run:

In [5]:
import time

for k in range(5, 13):
    n = 2 ** k
    
    # Create 2 matrices of size n x n
    A = np.random.rand(n, n)
    B = np.random.rand(n, n)
    
    # Compute and time the product A @ B
    t0 = time.time()
    A @ B
    t1 = time.time() - t0
    
    print(n, t1)

32 0.15065789222717285
64 0.0023539066314697266
128 0.000240325927734375
256 0.0008928775787353516
512 0.0038280487060546875
1024 0.020832061767578125
2048 0.14842605590820312
4096 1.0114610195159912


### Printing formatted strings

In the example above, we can see that printing floating point numbers can be fairly unreadable -- by default, many significant digits are displayed. The `.format` method can be used to print nicely formatted strings instead.

Here is a basic example:

In [ ]:
n = 3
k = 5
s = 'The value of n is {}, and the value of k is {}.'.format(n, k)
print(s)

Each input argument of `.format` corresponds to a pair of curly brackets `{}` in the string, in the same order. The value of each variable is then substituted in the string at the correct place. We can also explicitly indicate the order in which the variables should be substituted, by adding an index in each bracket:

In [ ]:
p = 33.5
s = 'p = {2}, n = {0} and k = {1}'.format(n, k, p)
print(s)

To limit the number of digits displayed for floats, we add `:.x` after the number indicating the position, where `x` is an integer. For example, to display $\pi$ with 5 significant digits:

In [ ]:
# Position 0: print 5 digits
s = 'pi = {0:.5}'.format(np.pi)
print(s)

Finally, the special character `'\n'` can be used to start a new line.

To summarise, using the same example as before:

In [ ]:
import time

for k in range(5, 13):
    n = 2 ** k
    
    # Create 2 matrices of size n x n
    A = np.random.rand(n, n)
    B = np.random.rand(n, n)
    
    # Compute and time the product A @ B
    t0 = time.time()
    A @ B
    t1 = time.time() - t0
    
    # Create a nice formatted string
    s = 'Dimension: n = {0}\nComputation time: {1:.4} seconds\n'.format(n, t1)
    print(s)

### Documentation links

* [time - Time access and conversions](https://docs.python.org/3/library/time.html)
* [time.time](https://docs.python.org/3/library/time.html#time.time)
* [Format string syntax](https://docs.python.org/3/library/string.html#formatstrings)
* [PyFormat](https://pyformat.info/)